language: node_js
node_js: stable
branches:
  only:
    - master
addons:
  chrome: stable
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
install:
  - npm install
script:
  - npm run unit
  - npm run build
